all:
  vars:
    install_kubernetes_control_plane_endpoint: "k8s-apiserver-nlb-4edad3d1048a2300.elb.ap-northeast-2.amazonaws.com"
  children:
    control_plane:
      hosts:
        master-1:
          ansible_host: i-0c0f855b56742e3f6
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/terraform-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region ap-northeast-2"'
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
        master-2:
          ansible_host: i-092418c72d033b686
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/terraform-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region ap-northeast-2"'
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
        master-3:
          ansible_host: i-0e26aa1cb33076a4b
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/terraform-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region ap-northeast-2"'
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
    worker_nodes:
      hosts:
        worker-1:
          ansible_host: i-0cb1cc68fdf26c840
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/terraform-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region ap-northeast-2"'
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
        worker-2:
          ansible_host: i-0ccab22a9ff1f1ed2
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/terraform-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region ap-northeast-2"'
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
