all:
  hosts:
    15.165.36.129:
      ansible_host: 15.165.36.129
      ansible_port: 22
      ansible_user: ubuntu
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_user: root
      type: light_sail
