# OS 체크
- name: Check OS ID
  shell: '. /etc/os-release && echo "$ID"'
  register: os_id
  changed_when: false

- name: Check OS version
  shell: '. /etc/os-release && echo "$VERSION_ID"'
  register: os_version
  changed_when: false

- name: Reject unsupported OS
  fail:
    msg: "지원하지 않는 OS 입니다. {{ os_id.stdout }} {{ os_version.stdout }}. (가능한 OS 목록 : [Ubuntu], [Rocky], [RHEL])"
  when: os_id.stdout not in ["ubuntu", "rocky", "rhel"]

- name: Reject unsupported OS version
  fail:
    msg: "지원하지 않는 OS version 입니다.: {{ os_id.stdout }} {{ os_version.stdout }}. (가능한 OS Version 목록 : Ubuntu 22.04, 24.04, 25.10, 26.04 / Rocky,RHEL supports 8, 9, 10)"
  when: >
    (os_id.stdout == "ubuntu" and os_version.stdout not in ["22.04", "24.04", "25.10", "26.04"]) or
    (os_id.stdout in ["rocky", "rhel"] and os_version.stdout.split('.')[0] not in ["8", "9", "10"])
  
# Architecture
- name: Check architecture
  command: uname -m
  register: architecture
  changed_when: false

- name: Reject unsupported architecture
  fail:
    msg: "지원하지 않는 아키텍쳐입니다. {{ architecture.stdout }}. (가능한 아키텍쳐 목록 :  x86_64/amd64, armhf, arm64/aarch64, s390x, ppc64le/ppc64el)"
  when: architecture.stdout not in ["x86_64", "amd64", "armhf", "arm64", "aarch64", "s390x", "ppc64le", "ppc64el"]

# Ubuntu 전용
- import_tasks: ubuntu.yml
  when: os_id.stdout == "ubuntu"

# RHEL / Rocky 전용
- import_tasks: redhat.yml
  when: os_id.stdout in ["rhel", "rocky"]
